defaults:
  - user: default
  - machine: local
  - callback: base 
  - data: bop
  - model: cnos #  cnos cnos_fast
  - _self_

save_dir: ${machine.root_dir}/results/${name_exp}
name_exp: cnos_exps
dataset_name: "manibot_2dgs" # manibot  ycbv manibot_svraster  manibot_2dgs  ycbv_real_subset_svraster  ycbv_real_subset_2dgs
templates_dir: /code/Data/BOP/
